dist: xenial

addons:
  apt:
    packages: ["nodejs", "npm"]

language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cd tests && ./run-tests.sh

cache: cargo
