dist: xenial

addons:
  apt:
    packages: ["nodejs", "npm"]

language: rust

rust:
  - stable

script:
  - cargo build --verbose
  - cargo test --verbose
  - tests/integration/scripts/run.sh

cache:
  cargo: true
  directories:
    - tests/integration/runner/node_modules
