dist: xenial

addons:
  apt:
    packages: ["nodejs", "npm"]

language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - ./tests/integration/scripts/run.sh

cache:
  - ./cargo
  - ./tests/integration/runner/node_modules
