[build.env]
passthrough = [
  "RUSTFLAGS"
]

[target.x86_64-unknown-linux-musl]
image = "valeriansaliou/sonic:cross-x86_64-unknown-linux-musl"

[target.armv7-unknown-linux-musleabihf]
image = "valeriansaliou/sonic:cross-armv7-unknown-linux-musleabihf"
